
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'SupportedBoards'
  strategy:
    matrix:
      zynq_zed_defconfig:
        CI_DEFCONFIG: 'zynq_zed_defconfig'
        ARCH: arm
      zynq_coraz7_defconfig:
        CI_DEFCONFIG: 'zynq_coraz7_defconfig'
        ARCH: arm
      zynq_adrv9361_defconfig:
        CI_DEFCONFIG: 'zynq_adrv9361_defconfig'
        ARCH: arm
      zynq_adrv9364_defconfig:
        CI_DEFCONFIG: 'zynq_adrv9364_defconfig'
        ARCH: arm
      zynq_zc702_defconfig:
        CI_DEFCONFIG: 'zynq_zc702_defconfig'
        ARCH: arm
      zynq_zc706_defconfig:
        CI_DEFCONFIG: 'zynq_zc706_defconfig'
        ARCH: arm
      xilinx_zynqmp_zcu102_rev1_0_defconfig:
        CI_DEFCONFIG: 'xilinx_zynqmp_zcu102_rev1_0_defconfig'
        ARCH: arm64
      adi_zynqmp_adrv9009_zu11eg_adrv2crr_fmc_defconfig:
        CI_DEFCONFIG: 'adi_zynqmp_adrv9009_zu11eg_adrv2crr_fmc_defconfig'
        ARCH: arm64
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - script: ./ci/run_build.sh
    displayName: "Build for $(CI_DEFCONFIG)"
